apiVersion: v1
kind: Service
metadata:
  name: travel
  labels:
    app: travel
spec:
  type: ClusterIP
  selector:
    app: travel
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: actuator
      port: 9091
      targetPort: actuator
