apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: travel-planner-kind-dev
  source:
    repoURL: https://github.com/protove/travel-gitops.git
    targetRevision: develop
    path: k8s/overlays/kind-dev/backend/maps-service
  destination:
    server: https://kubernetes.default.svc
    namespace: travel-planner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
