apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travel-planner
resources:
- ../../../../base/backend/identity-service
- serviceaccount.yaml
- hpa.yaml
patches:
- path: deployment.patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: identity
configMapGenerator:
- name: identity-config
  literals:
  - SPRING_PROFILES_ACTIVE=prod
  - SERVER_PORT=8080
  - MANAGEMENT_SERVER_PORT=9091
  - LOGGING_FILE_NAME=/var/log/identity-service/identity-service.log
  - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.dev-eks.kdt-travelplanner.internal:5432/travel_diary_dev?currentSchema=identity
  - SPRING_DATA_REDIS_HOST=master.kdt-travelplanner-dev-redis.ftc50s.apn2.cache.amazonaws.com
  - SPRING_DATA_REDIS_PORT=6379
  - TRAVEL_SERVICE_BASE_URL=http://travel:8080
  - CORS_ALLOWED_ORIGINS=https://kdt-travelplanner.protove.net
  - PROFILE_IMAGE_STORAGE_ENABLED=true
  - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=70.0 -XX:+UseG1GC
  - JWT_ISSUER=identity-service
  - SPRING_DATA_REDIS_USERNAME=default
  - SPRING_DATA_REDIS_SSL_ENABLED=true
  - PROFILE_IMAGE_STORAGE_REGION=ap-northeast-2
  - PROFILE_IMAGE_STORAGE_BUCKET=kdt-travelplanner-dev-profile-images-419496180357
  - PROFILE_IMAGE_PUBLIC_BASE_URL=https://d2s3iciy69ka0i.cloudfront.net
  - OAUTH_ALLOWED_REDIRECT_ORIGINS=https://kdt-travelplanner.protove.net
  - OAUTH_FRONTEND_REDIRECT_URL=https://kdt-travelplanner.protove.net/auth/callback/
  - GOOGLE_OAUTH_REDIRECT_URI=https://api.kdt-travelplanner.protove.net/api/v1/auth/oauth2/google/callback
  - NAVER_OAUTH_REDIRECT_URI=https://api.kdt-travelplanner.protove.net/api/v1/auth/oauth2/naver/callback
- name: identity-alloy-config
  files:
  - config.alloy
