apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: travel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: travel
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: travel
      target:
        type: Utilization
        averageUtilization: 60
