apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-dev-eks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: travel-planner-dev-eks
  source:
    repoURL: https://github.com/KDT-TravelPlanner/travel-gitops.git
    targetRevision: develop
    path: k8s/overlays/dev-eks/workload
  destination:
    server: https://kubernetes.default.svc
    namespace: travel-planner
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
